/// <reference path="jquery-3.4.1.js" />
/// <reference path="modernizr-2.8.3.js" />
/// <autosync enabled="true" />
/// <reference path="../bundles/bootstrap/js/bootstrap.min.js" />
/// <reference path="../bundles/bootstrapselect/js/bootstrap-select.min.js" />
/// <reference path="../bundles/chartistjs/dist/chartist.js" />
/// <reference path="../bundles/chartjs/chart.bundle.js" />
/// <reference path="../bundles/datepicker/js/bootstrap-datepicker.min.js" />
/// <reference path="../bundles/dropzone/dropzone.js" />
/// <reference path="../bundles/dropzone/dropzone-amd-module.js" />
/// <reference path="../bundles/footable/js/footable.all.min.js" />
/// <reference path="../bundles/jquery/js/jquery-2.2.4.min.js" />
/// <reference path="../bundles/nifty/v2.5/js/nifty.min.js" />
/// <reference path="../bundles/nifty/v2.5/plugins/bootbox/js/bootbox.min.js" />
/// <reference path="../bundles/nifty/v2.5/plugins/bootbox/js/ui-modals.js" />
/// <reference path="../bundles/nifty/v2.5/plugins/datatables/js/datatables.bootstrap.js" />
/// <reference path="../bundles/nifty/v2.5/plugins/datatables/js/datatables.responsive.min.js" />
/// <reference path="../bundles/nifty/v2.5/plugins/datatables/js/jquery.datatables.js" />
/// <reference path="../bundles/nifty/v2.5/plugins/datatables/js/tables-datatables.js" />
/// <reference path="../bundles/repute/js/repute-scripts.js" />
/// <reference path="../bundles/repute/plugins/parsley-validation/js/parsley.min.js" />
/// <reference path="../bundles/repute/plugins/slick/js/slick.min.js" />
/// <reference path="../bundles/repute/plugins/stellar/js/jquery.stellar.min.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/B.2.The Pig/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/B.2.The Pig/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/B.2.The Pig/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/B.2.The Pig/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/B.2.The Pig/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/B.2.The Pig/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/B.2.The Pig/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/ThePigPublished/The Pig - Narrative Example output/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/ThePigPublished/The Pig - Narrative Example output/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/ThePigPublished/The Pig - Narrative Example output/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/ThePigPublished/The Pig - Narrative Example output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/ThePigPublished/The Pig - Narrative Example output/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/ThePigPublished/The Pig - Narrative Example output/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/ThePigPublished/The Pig - Narrative Example output/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/B.2.The Pig.Narrative/ThePigPublished/The Pig - Narrative Example output/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/B.3.Whales See with Their Ears.Informational/WhalesSeeWithTheirEars/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/B.3.Whales See with Their Ears.Informational/WhalesSeeWithTheirEars/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/B.3.Whales See with Their Ears.Informational/WhalesSeeWithTheirEars/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/B.3.Whales See with Their Ears.Informational/WhalesSeeWithTheirEars/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/B.3.Whales See with Their Ears.Informational/WhalesSeeWithTheirEars/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/B.3.Whales See with Their Ears.Informational/WhalesSeeWithTheirEars/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/B.3.Whales See with Their Ears.Informational/WhalesSeeWithTheirEars/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/B.3.Whales See with Their Ears.Informational/WhalesSeeWithTheirEars/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/C.1.The Rainbow.Opinion V2/C.1.The Rainbow.Opinion/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/C.1.The Rainbow.Opinion V2/C.1.The Rainbow.Opinion/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/C.1.The Rainbow.Opinion V2/C.1.The Rainbow.Opinion/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/C.1.The Rainbow.Opinion V2/C.1.The Rainbow.Opinion/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/C.1.The Rainbow.Opinion V2/C.1.The Rainbow.Opinion/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/C.1.The Rainbow.Opinion V2/C.1.The Rainbow.Opinion/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/C.1.The Rainbow.Opinion V2/C.1.The Rainbow.Opinion/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/C.1.The Rainbow.Opinion V2/C.1.The Rainbow.Opinion/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/C.2.Reading.OpinionV2/C.2.Reading.OpinionV2/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/D. Dinosaurs.Informational/d. Dinosaurs/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/slides/5rwaMQGuC6R.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/slides/5wI2tLvbY0r.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/slides/6oymTRPEmtR.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/slides/6VrjJm8uG4r.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/E. A Whale of a Tale. Narrative V2/A Whale of a Tale (Narrative, E) output/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Nana Upstairs and Nana Downstairs.Response/Nana Upstairs and Nana Downstairs (Response, Level E)   output/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/slides/5rwaMQGuC6R.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/slides/5wI2tLvbY0r.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/slides/6oymTRPEmtR.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/slides/6VrjJm8uG4r.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/A Whale of a Tale Published 2/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/slides/5rwaMQGuC6R.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/slides/5wI2tLvbY0r.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/slides/6oymTRPEmtR.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/slides/6VrjJm8uG4r.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/E.Whale of a Tale.Narrative/Whale of a Tale Published V2/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/F.The Battle of Little Big Horn. Informational/F.1.The Battle of Little Big Horn/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/G.2.Gemstone Mining with Dad.Narrative V2/G.2.Gemstone Mining with Dad.Narrative V2 output/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/H.On the Boat with Cromwell.Narrative V2/H.On the Boat with Cromwell.Narrative V2 output/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/H.The Battle Cry of Freedom.Informational Narrative/H.The Battle Cry of Freedom.Informational Narrative output/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/I.2.Letter to State Board of Education.Argument V2/I.2.Letter to State Board of Education.Argument V2 output/story_content/user.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/data.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/fonts.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/masks.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/player_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/mobile/storyline_compiled.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/story_content/frame.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/story_content/story.js" />
/// <reference path="../Content/InteractiveMentorText2/J.MARIA.Poetry/Maria (Poetry, Level J) output/story_content/user.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/data.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/fonts.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/masks.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/player_compiled.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/slides/5rwaMQGuC6R.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/slides/5wI2tLvbY0r.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/slides/6oymTRPEmtR.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/slides/6VrjJm8uG4r.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/story_content/frame.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/story_content/story.js" />
/// <reference path="../MentorTexts/A Whale of a Tale (Narrative, E)/story_content/user.js" />
/// <reference path="../MentorTexts/C.1.The Rainbow.Opinion NEW/mobile/data.js" />
/// <reference path="../MentorTexts/C.1.The Rainbow.Opinion NEW/mobile/fonts.js" />
/// <reference path="../MentorTexts/C.1.The Rainbow.Opinion NEW/mobile/masks.js" />
/// <reference path="../MentorTexts/C.1.The Rainbow.Opinion NEW/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/C.1.The Rainbow.Opinion NEW/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/C.1.The Rainbow.Opinion NEW/story_content/frame.js" />
/// <reference path="../MentorTexts/C.1.The Rainbow.Opinion NEW/story_content/story.js" />
/// <reference path="../MentorTexts/C.1.The Rainbow.Opinion NEW/story_content/user.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/data.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/fonts.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/masks.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/player_compiled.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/story_content/frame.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/story_content/story.js" />
/// <reference path="../MentorTexts/C.2.Reading.OpinionV2 output/story_content/user.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/data.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/fonts.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/masks.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/Dinosaurs/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/Dinosaurs/story_content/frame.js" />
/// <reference path="../MentorTexts/Dinosaurs/story_content/story.js" />
/// <reference path="../MentorTexts/Dinosaurs/story_content/user.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/data.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/fonts.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/masks.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/player_compiled.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/story_content/frame.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/story_content/story.js" />
/// <reference path="../MentorTexts/G.2.Gemstone Mining with Dad/story_content/user.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/data.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/fonts.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/masks.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/player_compiled.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/story_content/frame.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/story_content/story.js" />
/// <reference path="../MentorTexts/H.On the Boat with Cromwell/story_content/user.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/data.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/fonts.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/masks.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/story_content/frame.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/story_content/story.js" />
/// <reference path="../MentorTexts/H.The Battle Cry of Freedom/story_content/user.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/data.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/fonts.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/masks.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/player_compiled.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/story_content/frame.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/story_content/story.js" />
/// <reference path="../MentorTexts/I.2.Letter to State Board of Education/story_content/user.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/data.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/fonts.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/masks.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/player_compiled.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/story_content/frame.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/story_content/story.js" />
/// <reference path="../MentorTexts/Maria (Poetry, Level J)/story_content/user.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/data.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/fonts.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/masks.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/player_compiled.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/story_content/frame.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/story_content/story.js" />
/// <reference path="../MentorTexts/Nana Upstairs and Nana Downstairs (Response, Level E)/story_content/user.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/data.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/fonts.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/masks.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/player_compiled.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/slides/5n9RcCgMa3L.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/slides/5nYB9RvjZnz.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/slides/5qbiK7f2iIQ.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/slides/5zyhiVADJFG.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/slides/65PKyXrDDTP.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/story_content/frame.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/story_content/story.js" />
/// <reference path="../MentorTexts/The Battle of Little Big Horn/story_content/user.js" />
/// <reference path="../MentorTexts/The Pig - Narrative Example output/mobile/data.js" />
/// <reference path="../MentorTexts/The Pig - Narrative Example output/mobile/fonts.js" />
/// <reference path="../MentorTexts/The Pig - Narrative Example output/mobile/masks.js" />
/// <reference path="../MentorTexts/The Pig - Narrative Example output/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/The Pig - Narrative Example output/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/The Pig - Narrative Example output/story_content/frame.js" />
/// <reference path="../MentorTexts/The Pig - Narrative Example output/story_content/story.js" />
/// <reference path="../MentorTexts/The Pig - Narrative Example output/story_content/user.js" />
/// <reference path="../MentorTexts/WhalesSeeWithTheirEarsPublished/mobile/data.js" />
/// <reference path="../MentorTexts/WhalesSeeWithTheirEarsPublished/mobile/fonts.js" />
/// <reference path="../MentorTexts/WhalesSeeWithTheirEarsPublished/mobile/masks.js" />
/// <reference path="../MentorTexts/WhalesSeeWithTheirEarsPublished/mobile/slides/5eYkCu6xnq8.js" />
/// <reference path="../MentorTexts/WhalesSeeWithTheirEarsPublished/mobile/storyline_compiled.js" />
/// <reference path="../MentorTexts/WhalesSeeWithTheirEarsPublished/story_content/frame.js" />
/// <reference path="../MentorTexts/WhalesSeeWithTheirEarsPublished/story_content/story.js" />
/// <reference path="../MentorTexts/WhalesSeeWithTheirEarsPublished/story_content/user.js" />
/// <reference path="jquery.unobtrusive-ajax.min.js" />
/// <reference path="jquery-ui-1.12.1.min.js" />
/// <reference path="searchtable.js" />
/// <reference path="teacher/classdatamodule.js" />
/// <reference path="teacher/interactivementortext.js" />
/// <reference path="teacher/uwcscorer.js" />
